### ISSUE TITLE
Cannot read property 'avatar_url' of null

### ISSUE THREAD

**Issue by rwetzeler** [jdcargile/ms-teams-notification#20]
Getting this error and I'm unsure why. 

TypeError: Cannot read property 'avatar_url' of null
    at Object.createMessageCard (/home/runner/work/_actions/jdcargile/ms-teams-notification/v1.3/dist/index.js:2446:16)
    at /home/runner/work/_actions/jdcargile/ms-teams-notification/v1.3/dist/index.js:3088:54
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/jdcargile/ms-teams-notification/v1.3/dist/index.js:3042:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Cannot read property 'avatar_url' of null

**Comment by rwetzeler** [comment]
sorry found this was already reported
