### ISSUE TITLE
TypeError: Cannot read property 'avatar_url' or null

### ISSUE THREAD

**Issue by mpconte** [jdcargile/ms-teams-notification#4]
Hello,

I can't reproduce this all the time, but maybe every other time I get the following error:

`TypeError: Cannot read property 'avatar_url' of null
    at Object.createMessageCard (C:\Users\rdbot\Desktop\action-runners\pdp_utils\_work\_actions\jdcargile\ms-teams-notification\v1.2\dist\index.js:2341:39)
    at C:\Users\rdbot\Desktop\action-runners\pdp_utils\_work\_actions\jdcargile\ms-teams-notification\v1.2\dist\index.js:2959:54
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\rdbot\Desktop\action-runners\pdp_utils\_work\_actions\jdcargile\ms-teams-notification\v1.2\dist\index.js:2906:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
##[error]Cannot read property 'avatar_url' of null`

**Comment by jdcargile** [comment]
@mpconte, do you have a user that is making commits that doesn't have an avatar? I can test this myself, but curious whether you're seeing any consistency from the users who commit who are seeing this issue?

**Comment by mpconte** [comment]
Yes, I'm performing the commit and I don't have an avatar in Microsoft Teams and I think someone else makes commits too but does have one

**Comment by jdcargile** [comment]
Thanks! I will take a look at this before the end of the week.

**Comment by jdcargile** [comment]
@mpconte, this is referencing the `author` of the commit in GitHub. I can see that you have an avatar in GitHub. Do you have an automated task that is creating the commits for you when it fails?

**Comment by mpconte** [comment]
@jdcargile My gihub workflow using this action doesn't run on commits, I have it set as a workflow_dispatch to checkout changes test it, build it and notify microsoft teams if the previous steps succeed.

**Comment by vtrusevich-incomm** [comment]
It looks like the issue is reproduced, whe the last commit is made by the user, whose email is not registered in GitHub

**Comment by vtrusevich-incomm** [comment]
@jdcargile , I see, that the author is taken from commit here https://github.com/jdcargile/ms-teams-notification/blob/a94290dd26cfcbe65dee7b4fbb171401d060ceef/dist/index.js#L2958. Looks like it is needed to add some checks on author existence before building the card

**Comment by dnepusb2** [comment]
Hey, I am running into the same issue....any good news?

**Comment by tsposato** [comment]
I'm also running into this issue, is there any progress on a fix?

**Comment by jdcargile** [comment]
Thank you all for your comments and questions. What would you suggest we use for the author if it is not found? Should I do a default avatar image or omit the image altogether?

**Comment by dnepusb2** [comment]
He JD, 
Thanks for the quick follow up.  From my perspective:

- Author undefined 
- Default avatar image

Cheers and thanks again!

**Comment by tsposato** [comment]
Sounds good to me.

--
Regards,
Terry Sposato
Engineering Manager
Freightmate Systems Pty Ltd
M: 0413922189

________________________________

**Comment by tsposato** [comment]
Sounds good to me.

**Comment by jdcargile** [comment]
This is fixed in #7. To pick up the new version, update your action version to use **v1.3**. See snippet below for more information.

`uses: jdcargile/ms-teams-notification@v1.3`

**Comment by tsposato** [comment]
I updated to 1.3 but I still received the same error.

**Comment by jdcargile** [comment]
> I updated to 1.3 but I still received the same error.

@tsposato, can you try using `uses: jdcargile/ms-teams-notification`? If that works I will create another release. I just pushed what I think will fix this finally.

**Comment by tsposato** [comment]
> @tsposato, can you try using `uses: jdcargile/ms-teams-notification` (don't provide the version so it grabs master)? If that works I will create another release. I just pushed what I think will fix this finally.
Will do. Not sure I'll get to test this until Monday as 5pm has rolled around but I'll let you know the outcome as soon as I can.

**Comment by tsposato** [comment]
The other weird thing is that the person in question does actually have an avatar set. Unless I'm misunderstanding the way it retrieves an avatar. Is there something strange about how GitHub does things avatar wise I'm not getting?

**Comment by jdcargile** [comment]
This might not be fixed then. Perhaps I need to query the user directly before trying to grab their information. I can look into this more tomorrow.

**Comment by tsposato** [comment]
Slightly different error when using master now @jdcargile :

TypeError: Cannot read property 'login' of null
    at Object.createMessageCard (/home/runner/work/_actions/jdcargile/ms-teams-notification/master/dist/index.js:2461:85)
    at /home/runner/work/_actions/jdcargile/ms-teams-notification/master/dist/index.js:3090:54
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/jdcargile/ms-teams-notification/master/dist/index.js:3044:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Cannot read property 'login' of null

**Comment by tsposato** [comment]
Ok, so after some more digging it turns out the user had incorrectly spelt their email in their git user.email settings on one of their clients, hence why the user isn't being linked to their github account correctly. I think it should still probably be 'caught' instead of just failing completely though. Maybe just grab the name from the commit message and use that default avatar.

**Comment by akshata-kenchanagudd** [comment]
Hi @jdcargile,

Getting the below error when using  "**uses: jdcargile/ms-teams-notification**" instead of  uses: jdcargile/ms-teams-notification@v1.3. Kindly suggest.
The workflow is not valid. .github/workflows/terraform-validate.yml (Line: 182, Col: 17): Expected format {org}/{repo}[/path]@ref. Actual 'jdcargile/ms-teams-notification' Input string was not in a correct format.

**Comment by stuartforrest-infinity** [comment]
@jdcargile can you release a v1.4 that includes this commit - https://github.com/jdcargile/ms-teams-notification/commit/3e536e08814945d8518044475b58e52e01881d02?

**Comment by gspindev** [comment]
@jdcargile  facing same issue - using v1.3

TypeError: Cannot read property 'avatar_url' of null
    at Object.createMessageCard (/home/runner/work/_actions/jdcargile/ms-teams-notification/v1.3/dist/index.js:2446:16)
    at /home/runner/work/_actions/jdcargile/ms-teams-notification/v1.3/dist/index.js:3088:54
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/jdcargile/ms-teams-notification/v1.3/dist/index.js:3042:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Cannot read property 'avatar_url' of null

**Comment by rwetzeler** [comment]
> The other weird thing is that the person in question does actually have an avatar set. Unless I'm misunderstanding the way it retrieves an avatar. Is there something strange about how GitHub does things avatar wise I'm not getting?

We experienced this exact problem.  When I dug in further, it appears that the author, was different than who committed... that author wasn't registered in GitHub from Name and email, but SSH keys are.. so he is a valid contributor on the repository, but GitHub doesn't recognize the email he committed with (because he didn't add that in his profile), yet his SSH key's re valid to commit.

I propose that if avatar_url fails, you put in a default avatar image, instead of failing the job.

![image](https://user-images.githubusercontent.com/159081/127664027-951dbeaf-ca18-42bd-a5e1-a47e53fb2f78.png)

**Comment by pythonInRelay** [comment]
> > The other weird thing is that the person in question does actually have an avatar set. Unless I'm misunderstanding the way it retrieves an avatar. Is there something strange about how GitHub does things avatar wise I'm not getting?
> 
> We experienced this exact problem. When I dug in further, it appears that the author, was different than who committed... that author wasn't registered in GitHub from Name and email, but SSH keys are.. so he is a valid contributor on the repository, but GitHub doesn't recognize the email he committed with (because he didn't add that in his profile), yet his SSH key's re valid to commit.
> 
> I propose that if avatar_url fails, you put in a default avatar image, instead of failing the job.
> 
> ![image](https://user-images.githubusercontent.com/159081/127664027-951dbeaf-ca18-42bd-a5e1-a47e53fb2f78.png)

Hi mate, have you got a pull request that shows how to fix this? Most of our users do not have avatars.

**Comment by mariam-alexander** [comment]
Is there a fix for this issue yet ?

**Comment by lumos94** [comment]
same here, started having this issue since yesterday! all was good until suddenly it stopped!
the weird thing is that this happens only to 1 of my projects. in the other projects it work fine!

**Comment by dennistex** [comment]
Having this issue since last week. Looks like [3e536e0](https://github.com/jdcargile/ms-teams-notification/commit/3e536e08814945d8518044475b58e52e01881d02) fixes it

**Comment by EvgeniyRub** [comment]
anibody fixed this issue already?

**Comment by bfernandes-d** [comment]
Any news on this bug ?

**Comment by dimitar-cp** [comment]
This started appearing today. Any news on the fix?

**Comment by LeonSnajdr** [comment]
I looked at the forks and searched for a fix, one fixed the bug in this pre-release #https://github.com/TBCTSystems/ms-teams-notification/releases/tag/v1.3.1

**Comment by LeonSnajdr** [comment]
Maybe someone can create a pull request if it works for you too.

**Comment by silveiratalita** [comment]
@LeonSnajdr, can you help me to understand how can I use this repo from TBCTSystems? I used the same way, but the reference stil ar the original repo, and the error continue happens.

**Comment by silveiratalita** [comment]
try this, for me it works!

 - name: "Microsoft Teams - Notification"
      uses: toko-bifrost/ms-teams-deploy-card@master
      if: always()
      with:
        github-token: ${{ github.token }}
        webhook-uri: ${{ secrets.YOUR_TEAMS_WEBHOOK }}
        timezone: America/Sao_Paulo

**Comment by elubikowski** [comment]
You have to have git user configured globally. I was using custom configuration without global settings. Adding as follows fixed the issue.
Obviously provide your values between double-quotes ;)

git config --global user.name "your_username"
git config --global user.email "your@email.com"

**Comment by gfrid** [comment]
this is still not fixed in 1.3 getting the same error, i think the owner of code does not continue to support this code
i will move to another once

TypeError: Cannot read property 'avatar_url' of null
    at Object.createMessageCard (/runner/_work/_actions/jdcargile/ms-teams-notification/v1.3/dist/index.js:2446:16)
    at /runner/_work/_actions/jdcargile/ms-teams-notification/v1.3/dist/index.js:3088:54
    at Generator.next (<anonymous>)
    at fulfilled (/runner/_work/_actions/jdcargile/ms-teams-notification/v1.3/dist/index.js:3042:58)
    at processTicksAndRejections (internal/process/task_queues.js:[9](https://github.com/nice-global-devops/TailoredCostOptimization/actions/runs/4053704845/jobs/6974636084#step:4:10)7:5)
Error: Cannot read property 'avatar_url' of null

**Comment by bkagan98** [comment]
Was this avatar_url issue ever fixed? We're still getting this error with v1.3...

**Comment by kimbalabhay** [comment]
> Was this avatar_url issue ever fixed? We're still getting this error with v1.3...

same here

**Comment by nmacri** [comment]
@bkagan98 @kimbalabhay Confirming that we are seeing the `avatar_url` issue fixed on v1.4
